//! Saved connection rows.

use rusqlite::{params, OptionalExtension};

use super::{engine_str, parse_engine, parse_ssl, ssl_str, Store};
use crate::error::Result;
use crate::model::ConnectionConfig;

impl Store {
    pub fn list_connections(&self) -> Result<Vec<ConnectionConfig>> {
        let conn = self.lock();
        let mut stmt = conn.prepare(
            "SELECT id, name, engine, host, port, username, database, file_path,
                    ssl_mode, color, read_only
             FROM connections ORDER BY sort_order, name",
        )?;
        let rows = stmt.query_map([], |r| {
            Ok(Some(ConnectionConfig {
                id: r.get("id")?,
                name: r.get("name")?,
                engine: match parse_engine(&r.get::<_, String>("engine")?) {
                    Some(e) => e,
                    // Unknown engine: most likely a row written by a newer
                    // build. Dropped from the list rather than guessed at,
                    // because guessing means opening a connection with the
                    // wrong wire protocol against the wrong port.
                    None => return Ok(None),
                },
                host: r.get("host")?,
                port: r.get::<_, i64>("port")? as u16,
                username: r.get("username")?,
                database: r.get("database")?,
                file_path: r.get("file_path")?,
                ssl_mode: parse_ssl(&r.get::<_, String>("ssl_mode")?),
                color: r.get("color")?,
                read_only: r.get::<_, i64>("read_only")? != 0,
            }))
        })?;
        Ok(rows
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .flatten()
            .collect())
    }

    pub fn get_connection(&self, id: &str) -> Result<Option<ConnectionConfig>> {
        // Reuses the list mapping rather than duplicating the column list;
        // the connection count is tiny by nature.
        Ok(self.list_connections()?.into_iter().find(|c| c.id == id))
    }

    /// Insert or update. The id is generated by the caller so the keychain entry
    /// and the row can be created together.
    pub fn upsert_connection(&self, c: &ConnectionConfig) -> Result<()> {
        let conn = self.lock();
        conn.execute(
            r#"
            INSERT INTO connections
                (id, name, engine, host, port, username, database, file_path,
                 ssl_mode, color, read_only)
            VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
            ON CONFLICT(id) DO UPDATE SET
                name = excluded.name,
                engine = excluded.engine,
                host = excluded.host,
                port = excluded.port,
                username = excluded.username,
                database = excluded.database,
                file_path = excluded.file_path,
                ssl_mode = excluded.ssl_mode,
                color = excluded.color,
                read_only = excluded.read_only
            "#,
            params![
                c.id,
                c.name,
                engine_str(c.engine),
                c.host,
                c.port as i64,
                c.username,
                c.database,
                c.file_path,
                ssl_str(c.ssl_mode),
                c.color,
                c.read_only as i64,
            ],
        )?;
        Ok(())
    }

    pub fn delete_connection(&self, id: &str) -> Result<()> {
        self.lock()
            .execute("DELETE FROM connections WHERE id = ?1", params![id])?;
        Ok(())
    }

    pub fn connection_exists(&self, id: &str) -> Result<bool> {
        let conn = self.lock();
        let found: Option<i64> = conn
            .query_row(
                "SELECT 1 FROM connections WHERE id = ?1",
                params![id],
                |r| r.get(0),
            )
            .optional()?;
        Ok(found.is_some())
    }
}
